from __future__ import annotations

import base64
import urllib.parse
import xml.etree.ElementTree as ET
import zlib
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from ..errors import DocumentError, SourceLocation


@dataclass(frozen=True, slots=True)
class DiagramSource:
    kind: str
    content: str
    location: SourceLocation | None = None


class DrawioDocument:
    """An mxGraph draw.io document, kept uncompressed when generated by this package."""

    def __init__(self, xml: str) -> None:
        self.xml = xml
        try:
            self.root = ET.fromstring(xml)
        except ET.ParseError as error:
            raise DocumentError(f"invalid draw.io XML: {error}") from error
        self.graph_model = self._find_graph_model()

    @classmethod
    def read(cls, path: str | Path) -> DrawioDocument:
        source = Path(path)
        if not source.exists():
            raise DocumentError(f"draw.io source does not exist: {source}")
        return cls(source.read_text(encoding="utf-8"))

    def _find_graph_model(self) -> ET.Element:
        if self.root.tag == "mxGraphModel":
            return self.root
        model = self.root.find(".//mxGraphModel")
        if model is not None:
            return model
        diagram = self.root.find(".//diagram")
        if diagram is not None and diagram.text and diagram.text.strip():
            try:
                payload = base64.b64decode(diagram.text.strip())
                inflated = zlib.decompress(payload, -15).decode("utf-8")
                decoded = urllib.parse.unquote(inflated)
                return ET.fromstring(decoded)
            except (ValueError, zlib.error, ET.ParseError) as error:
                raise DocumentError(
                    "draw.io document contains an invalid compressed diagram"
                ) from error
        raise DocumentError("draw.io document does not contain mxGraphModel")

    def validate_native_graph(self, *, reject_image_cells: bool = False) -> None:
        cells = self.graph_model.findall(".//mxCell")
        vertices = [cell for cell in cells if cell.get("vertex") == "1"]
        edges = [cell for cell in cells if cell.get("edge") == "1"]
        if not vertices:
            raise DocumentError("draw.io diagram has no editable vertex cells")
        for edge in edges:
            if not edge.get("source") or not edge.get("target"):
                raise DocumentError("draw.io edge must reference editable source and target cells")
        serialized = ET.tostring(self.graph_model, encoding="unicode").lower()
        if "mermaiddata" in serialized or 'data="mermaid"' in serialized:
            raise DocumentError("Mermaid plugin payloads are not native editable draw.io cells")
        if reject_image_cells:
            for cell in vertices:
                style = cell.get("style", "").lower()
                if "shape=image" in style or "image=data:" in style:
                    raise DocumentError(
                        "Mermaid conversion produced an image cell instead of native cells"
                    )

    def write(self, path: str | Path) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(self.xml, encoding="utf-8")
        return destination


DiagramConverter = Callable[[DiagramSource], DrawioDocument]


class DiagramConverterRegistry:
    """Maps source languages to native draw.io converters without coupling them to DOCX."""

    def __init__(self) -> None:
        self._converters: dict[str, DiagramConverter] = {}

    def add(self, kind: str, converter: DiagramConverter, *, replace: bool = False) -> None:
        normalized = kind.strip().lower()
        if not normalized:
            raise ValueError("diagram source kind cannot be empty")
        if normalized in self._converters and not replace:
            raise ValueError(f"diagram converter already registered: {normalized}")
        self._converters[normalized] = converter

    def supports(self, kind: str | None) -> bool:
        return bool(kind and kind.strip().lower() in self._converters)

    def convert(self, source: DiagramSource) -> DrawioDocument:
        kind = source.kind.strip().lower()
        converter = self._converters.get(kind)
        if converter is None:
            raise DocumentError(
                f"no diagram converter registered for source kind: {kind}", source.location
            )
        try:
            document = converter(source)
            document.validate_native_graph(reject_image_cells=kind == "mermaid")
            return document
        except DocumentError as error:
            if error.location is not None or source.location is None:
                raise
            raise DocumentError(error.message, source.location) from error


def _drawio_converter(source: DiagramSource) -> DrawioDocument:
    return DrawioDocument(source.content)


def default_diagram_registry() -> DiagramConverterRegistry:
    from .mermaid import convert_mermaid_flowchart

    registry = DiagramConverterRegistry()
    registry.add("drawio", _drawio_converter)
    registry.add("mermaid", convert_mermaid_flowchart)
    return registry
